### ISSUE TITLE
SP non server Disappearing Grid storage

### ISSUE THREAD

**Issue by Pultex** [starforcraft/Universal-Grid#10]
There was no error in the log or crash so not sure what to do but tell you what happened
I am on ATM8 latest might be the whole reason for the problems
forgeVersion, 43.2.3
minecraft 1.19.2

It is not a error or maybe even a bug
I just noticed that when moving a lot of items out of the wireless grid to transfer it to 
another storage system the storage disappeared all items were gone
When I tried to connect to the grid again I saw the portable storage terminals items instead of the main systems 
Then closed it worried it would corrupt something
opened it again nothing was there 
waited a little then it all returned this did not just effect the wireless but the RS system as a whole
grids could not see the systems items even ones on external storage
there is power millions of RF per tick

Do you think this is a bug in RS itself or is there some sort of buffer between your mod and it to cause this
RS had just found a problem with another mod that can be avoided by using server setup

**Comment by starforcraft** [comment]
It's impossible to tell if this is a bug in RS itself or in this addon mod without having any error/crash or a way to reproduce it, sorry
