### ISSUE TITLE
Crash on client startup 1.18.2

### ISSUE THREAD

**Issue by GnomTocha** [starforcraft/Universal-Grid#11]
Forge: 40.2.0
After installing the mod, the assembly stopped running.
Going through the mods, I found out that the combined presence of mods such as Patchouli, Create and Architectury causes a crash. You can also add REIPluginCompatibilities to the list.
Checked on different versions of Forge.
![image](https://user-images.githubusercontent.com/75666317/224503286-24cda2d4-fea2-4f4b-af81-7b792761b6e2.png)

[crash-2023-03-11_19.29.06-fml.txt](https://github.com/starforcraft/Universal-Grid/files/10949079/crash-2023-03-11_19.29.06-fml.txt)
[latest.log](https://github.com/starforcraft/Universal-Grid/files/10949081/latest.log)

**Comment by starforcraft** [comment]
The logs you provided claim that Refined Storage Addons is the cause of this crash

**Comment by GnomTocha** [comment]
I do not know how it works, but the assembly started without removing or replacing mods. On your recommendation, I will delete the file. Refined Storage Addons was installed due to an optional dependency of Universal Grid. Thanks for the answer. Until I close the topic.
