### ISSUE TITLE
Spam in Console Log

### ISSUE THREAD

**Issue by Okimo** [starforcraft/Universal-Grid#3]
Version: universalgrid-1.16.5-0.1221.jar

When grid is open there is spam in log:
[Server thread/INFO] [universalgrid/]: asd
![image](https://user-images.githubusercontent.com/12627805/140964459-38be3e61-03f4-4ef0-b816-544ee3d007b0.png)

**Comment by starforcraft** [comment]
Oh fuck sorry I accidentally uploaded the wrong file

**Comment by starforcraft** [comment]
https://www.curseforge.com/minecraft/mc-mods/universal-grid/files/3520543
