### ISSUE TITLE
Inventory and grid get scrambled, fluid grid mode doesn't work

### ISSUE THREAD

**Issue by Brycey92** [starforcraft/Universal-Grid#5]
With RS 1.9.16 and RS Addons 0.7.4, opening the Universal Grid causes the player inventory to become scrambled until a relog, and the item grid also becomes scrambled, displaying the wrong items with the wrong quantities. Additionally, the fluid grid mode just displays the item grid.

**Comment by starforcraft** [comment]
Log? And are you on server?

**Comment by saquili** [comment]
I have similar issiue, with crafting grid mode I have doubled tool bar, and sometimes some random items are placed in crafting area. Fluid grid does not work. I am playing on all the mods 6 server
![bug](https://user-images.githubusercontent.com/52722034/144304076-8615a631-b68d-4962-b11d-99f5c945a1f8.png)
.

**Comment by Brycey92** [comment]
Yes, this is on a server. Here are logs where I reproduced the issues. I started reproducing the issue at
`[12:18:44] [Render thread/INFO]: [CHAT] Gave 1    [Chargepad] to Brycey92`
on the client and finished when I said "test complete" in chat (the next line in the client's log.)
[server logs.zip](https://github.com/starforcraft/Universal-Grid/files/7644740/server.logs.zip)
[client latest.zip](https://github.com/starforcraft/Universal-Grid/files/7644742/client.latest.zip)

**Comment by devorig** [comment]
On singleplayer, same versions. This makes the items displayed in the universal grid very jumpy. Like the sorting is going back on itself. Especially the fluid grid, where items are added too.

**Comment by starforcraft** [comment]
Sorry for taking so long but heres the fix https://www.curseforge.com/minecraft/mc-mods/universal-grid/files/3696626
