### ISSUE TITLE
Crash on latest version if the grid isn't in my hand

### ISSUE THREAD

**Issue by chlorofomduck** [starforcraft/Universal-Grid#7]
On Project Architect 1.9 MC version 1.16.5 Forge version 36.2.31, I manually switched to the latest version of Universal Grid, 1.01 after the recent update. As long as the grid is in my hand it works great, but if I try to use the hotkey while it's in my inventory or in a curio slot, it crashes.

Playing single player

Crash log: https://bytebin.lucko.me/sJAezID9o4

**Comment by starforcraft** [comment]
https://www.curseforge.com/minecraft/mc-mods/universal-grid/files/3709782
