### ISSUE TITLE
Crashes Refined Storage Addons

### ISSUE THREAD

**Issue by ZEROX7** [starforcraft/Universal-Grid#8]
wehn launching with your mod installed refined storage addons crashes minecraft 1.18.2
forge 40.1.59
[crash-2022-07-24_13.08.27-fml.txt](https://github.com/starforcraft/Universal-Grid/files/9175652/crash-2022-07-24_13.08.27-fml.txt)

**Comment by ZEROX7** [comment]
for some reason adding your mod makes other mods crash but not ever time i load up this time create alloyed crashed XD
[crash-2022-07-24_13.30.26-fml.txt](https://github.com/starforcraft/Universal-Grid/files/9175667/crash-2022-07-24_13.30.26-fml.txt)

**Comment by starforcraft** [comment]
This has nothing to do with Universal Grid. Are you maybe using a cracked Launcher?

**Comment by ZEROX7** [comment]
using curseforge itself but idk hadnt that issue before thats why i reported it here
